@startuml
class ViewModel {
  {field} +column : ViewModelColumn
  {field} +task : ViewModelTask
  {field} +env : ViewModelEnvironment
  {field} +userSetting : ViewModelUserSetting
}

class ViewModelColumn {
  {field} +display : ko.observable(Boolean)
  +columns : Column[]
  {field} +projects : ko.observableArray(Project)
  {field} +selectedColumn : ko.observable(AbstractColumn)
  {field} +renameProject : ko.observable(Project)
}

class ViewModelTask {
  {field} +incompleteTasks : ko.observableArray(Task)
  {field} +completedTasks : ko.observableArray(Task)
  {field} +openCompleteTaskFlag : ko.observable(Number)
}

class ViewModelEnvironment {
  {field} +isMobile : ko.observable(Boolean)
}

class ViewModelUserSetting {
  {field} +display : ko.observable(Boolean)
  {field} +displayIcon : ko.observable(Boolean)
  {field} +imageFileMaxSize : ko.observable(String)
  {field} +backgroundImageHash : ko.observable(String)
  +availableFontFamilies : FontFamily[]
  {field} +selectedFontFamily : ko.observable(String)
}

class AbstractColumn {
  {field} +name : ko.observable(String)
  {field} +color : ko.observable(String)
  +icon : String
  +get projectId() : Number
  +get completetionDateRangeStart() : String
  +get completetionDateRangeEnd() : String
  +get taskStatus() : Number
}

class Project {
  +id : Number
  +get projectId() : Number
}

class Column {
  -#completetionDateRangeStart : Number
  -#completetionDateRangeEnd : Number
  -#taskStatus : Number
  {field} +countIncompleteTasks : ko.observable(Number)
  +daysLaterToDateStr(daysLater) : String
  +get completetionDateRangeStart() : String
  +get completetionDateRangeEnd() : String
  +get taskStatus() : Number
}

class Task {
  +id : Number
  +project : Project
  +value : String
  +completetionDate : String
  +status : Number
  +get isCompleted() : Boolean
  +get isExpired() : Boolean
}

class HeadViewModel {
  {field} +fontFamilyHref : ko.computed(String)
}

class FontFamily {
  +name : String
  +fontFamily : String
}

AbstractColumn <|-u- Column
AbstractColumn <|-u- Project
ViewModel "1" -- "1" ViewModelColumn
ViewModel "1" -- "1" ViewModelTask
ViewModel "1" -- "1" ViewModelEnvironment
ViewModel "1" -- "1" ViewModelUserSetting
ViewModelColumn "1" *-- "5" Column
ViewModelColumn "1" o-- "0..*" Project
ViewModelTask "1" o-- "0..*" Task
ViewModelUserSetting "1" *-- "4" FontFamily
@enduml
